### ISSUE TITLE
`ImportError: cannot import name 'Self' from 'typing_extensions'` due to old typing-extensions

### ISSUE THREAD

**Issue by gkreitz** [stripe/stripe-python#1035]
### Describe the bug

It seems like your code is using a feature of typing-extensions (`Self`) which is newer than the requirements listed in `setup.py`. You depend on `typing_extensions > 3.7.2`, but as far as I can tell, `Self` was added in 4.0.0. If one has an older version of typing-extensions and python < 3.11, `import stripe` fails:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gkreitz/foo/venv/lib/python3.10/site-packages/stripe/__init__.py", line 37, in <module>
    from stripe.api_resources import *  # pyright: ignore # noqa
  File "/home/gkreitz/foo/venv/lib/python3.10/site-packages/stripe/api_resources/__init__.py", line 7, in <module>
    from . import abstract
  File "/home/gkreitz/foo/venv/lib/python3.10/site-packages/stripe/api_resources/abstract/__init__.py", line 19, in <module>
    from stripe.api_resources.abstract.listable_api_resource import (
  File "/home/gkreitz/foo/venv/lib/python3.10/site-packages/stripe/api_resources/abstract/listable_api_resource.py", line 4, in <module>
    from stripe.api_resources.list_object import ListObject
  File "/home/gkreitz/foo/venv/lib/python3.10/site-packages/stripe/api_resources/list_object.py", line 2, in <module>
    from typing_extensions import Self
ImportError: cannot import name 'Self' from 'typing_extensions' (/home/gkreitz/foo/venv/lib/python3.10/site-packages/typing_extensions.py)
```

### To Reproduce

```sh
python3 -m venv venv
source venv/bin/activate
pip install typing-extensions==3.10.0.2 # any version that satisfies the requirement, but is below 4.0.0
pip install stripe
python -m stripe # or any other way to import stripe
```

Note that this likely can't be reproduced with Python 3.11, as `Self` was added to the language in that release.

### Expected behavior

Expected to import cleanly.

### OS

Linux, Ubuntu 22.04.3 LTS

### Language version

Python 3.10.12

### Library version

stripe-6.2.0

### API version

N/A

**Comment by anniel-stripe** [comment]
Hi @gkreitz, thanks for bringing this issue to our attention. I've updated the requirement in https://github.com/stripe/stripe-python/pull/1042 and released in [v6.3.0](https://github.com/stripe/stripe-python/releases/tag/v6.3.0).
