### ISSUE TITLE
Getting InvalidRequestError on attempting to create Bitcoin charges

### ISSUE THREAD

**Issue by sr-murthy** [stripe/stripe-python#167]
Hi

I'm implementing Bitcoin payment functionality for my company's cloud platform services - we already accept Stripe cards.  For testing Bitcoin we are using our Stripe account's test API keys.  I am having problems in creating Bitcoin charges because I keep getting bad request errors - here's the charge creation statement (using a fresh, i.e. non-expired Bitcoin receiver address) and the resulting traceback on the shell:
```
>>> charge = stripe.Charge.create(
...      amount = 600,
...      currency = 'USD',
...      source='test_gJxwIuRsA7YBfFP3nWFzwb9hWEjmj',
...      description='foo@bar.com'
...    )
/usr/local/lib/python2.6/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/stripe/resource.py", line 344, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/usr/local/lib/python2.6/dist-packages/stripe/api_requestor.py", line 141, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/usr/local/lib/python2.6/dist-packages/stripe/api_requestor.py", line 269, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/usr/local/lib/python2.6/dist-packages/stripe/api_requestor.py", line 156, in handle_api_error
    rbody, rcode, resp, rheaders)
```

**Comment by sr-murthy** [comment]
I've just noticed something.  Our Bitcoin payment functionality is implemented in a split-style: the Bitcoin payment details,
including the Bitcoin receiver address, URI, QR code etc., is generated client-side by JS, and the charge creation and
submission is done server-side by Python code.  On the Python shell I note that if I manually create a test receiver and
create a charge on that, the charge is successfully created, but this is not what we want: the receiver must be created
client side by the JS, and the receiver ID is posted to server-side and that receiver ID is used by Python code to
create and submit the charge to Stripe.

**Comment by sr-murthy** [comment]
It looks like I was passing the Bitcoin receiver address for the `source` field in the charge creation.  This has been fixed, and charge creation now works.  Sorry for the confusion.
