### ISSUE TITLE
Multiple test_integration test failures (1.30.0)

### ISSUE THREAD

**Issue by koobs** [stripe/stripe-python#213]
The following tests are failing in 1.30.0:

```
test_invalid_credentials (test_integration.AuthenticationErrorTest) ... ERROR

ERROR: test_invalid_credentials (test_integration.AuthenticationErrorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/test/test_integration.py", line 132, in test_invalid_credentials
    self.assertTrue(e.request_id.startswith('req_'))
AttributeError: 'NoneType' object has no attribute 'startswith'
```
The rest:
```
test_declined_card_props (test_integration.CardErrorTest) ... ERROR
test_list_accessors (test_integration.FunctionalTests) ... ERROR
test_none_values (test_integration.FunctionalTests) ... ERROR
test_raise (test_integration.FunctionalTests) ... ERROR
test_refresh (test_integration.FunctionalTests) ... ERROR
test_response_headers (test_integration.FunctionalTests) ... ERROR
test_run (test_integration.FunctionalTests) ... ERROR
test_unicode (test_integration.FunctionalTests) ... ERROR
test_invalid_data (test_integration.InvalidRequestErrorTest) ... ERROR
test_nonexistent_object (test_integration.InvalidRequestErrorTest) ... ERROR
test_list_accessors (test_integration.PycurlFunctionalTests) ... ERROR
test_none_values (test_integration.PycurlFunctionalTests) ... ERROR
test_raise (test_integration.PycurlFunctionalTests) ... ERROR
test_refresh (test_integration.PycurlFunctionalTests) ... ERROR
test_response_headers (test_integration.PycurlFunctionalTests) ... ERROR
test_run (test_integration.PycurlFunctionalTests) ... ERROR
test_unicode (test_integration.PycurlFunctionalTests) ... ERROR
test_list_accessors (test_integration.RequestsFunctionalTests) ... ERROR
test_none_values (test_integration.RequestsFunctionalTests) ... ERROR
test_raise (test_integration.RequestsFunctionalTests) ... ERROR
test_refresh (test_integration.RequestsFunctionalTests) ... ERROR
test_response_headers (test_integration.RequestsFunctionalTests) ... ERROR
test_run (test_integration.RequestsFunctionalTests) ... ERROR
test_unicode (test_integration.RequestsFunctionalTests) ... ERROR
```

Fail identically with:

```
Traceback (most recent call last):
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/test/test_integration.py", line 144, in test_declined_card_props
    stripe.Charge.create(amount=100, currency='usd', card=EXPIRED_CARD)
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/resource.py", line 407, in create
    response, api_key = requestor.request('post', url, params, headers)
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/api_requestor.py", line 138, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/api_requestor.py", line 270, in interpret_response
    self.handle_api_error(rbody, rcode, resp, rheaders)
  File "/usr/home/user/repos/freebsd/ports/finance/py-stripe/work/stripe-1.30.0/stripe/api_requestor.py", line 168, in handle_api_error
    rheaders)
APIError: Request req_<uniqueid>: Your test data is in the process of being deleted.  Once this is complete you will be able to make test mode requests again.
```

**Comment by brandur** [comment]
Ugh. We activated a test data deletion process for the account and unfortunately, it either never came back or is still running. I'm looking into getting a fix for this out today, with the worst case scenario just rolling us a new account for the tests.

Sorry about the trouble.

**Comment by koobs** [comment]
Not at all, good to know it's only a transient issue, thank you @brandur :)

Looking forward, should/could these tests be mocked, or the request/responses be emulated, say with `vcrpy`, `pretend` or similar, or do they *really* need to test the *actual* API ?

**Comment by brandur** [comment]
> Looking forward, should/could these tests be mocked, or the request/responses be emulated, say with vcrpy, pretend or similar, or do they really need to test the actual API ?

Oh man, they absolutely don't and _shouldn't be_ hitting the actual API. We've got our eye on fixing this, but unfortunately it's an anti-pattern that's been introduced across almost every language binding, and so we have a little bit of a hole to dig ourselves out of before things are going to be fixed. Stay tuned :)

**Comment by brandur** [comment]
And also, the deletion process is still running. The good news is that we fixed a pretty serious bug in it yesterday, so it's making much better progress now. I'm going to see where it gets to by Monday, and decide whether to roll a new test account then if it looks like we have to.

**Comment by olivierbellone** [comment]
Tests seems to be running ok now, so I'm going to go ahead and close this one.
