### ISSUE TITLE
tests: test_is_deletable fails / ResourceWarnings

### ISSUE THREAD

**Issue by blueyed** [stripe/stripe-python#405]
I am seeing 10 test failures (for `test_is_deletable`) - are they related to recent changes in stripe-mock (I just installed the master version as per the README):

```
======================================================================
FAIL: test_is_deletable (tests.api_resources.test_account.AccountExternalAccountsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_account.py", line 193, in test_is_deletable
    self.assertIsInstance(resource, stripe.BankAccount)
AssertionError: <StripeObject id=this_is_a_fake_id_for_deleted_object at 0x7fe455f47e60> JSON: {
  "deleted": true,
  "id": "this_is_a_fake_id_for_deleted_object"
} is not an instance of <class 'stripe.api_resources.bank_account.BankAccount'>

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_account.AccountTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_account.py", line 95, in test_is_deletable
    '/v1/accounts/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/accounts/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe455dfeb70>, 'delete', '/v1/accounts/acct_1BoJ2AKrZ43eBVAb', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_product.ProductTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_product.py", line 64, in test_is_deletable
    '/v1/products/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/products/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe45588e470>, 'delete', '/v1/products/prod_CCiTUrJyglMaGj', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_customer.CustomerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_customer.py", line 65, in test_is_deletable
    '/v1/customers/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/customers/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe455ac0630>, 'delete', '/v1/customers/cus_CCiTI4Tpghl0nK', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_coupon.CouponTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_coupon.py", line 66, in test_is_deletable
    '/v1/coupons/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/coupons/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe4556da9b0>, 'delete', '/v1/coupons/25OFF', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_apple_pay_domain.ApplePayDomainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_apple_pay_domain.py", line 43, in test_is_deletable
    '/v1/apple_pay/domains/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/apple_pay/domains/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe4588d8438>, 'delete', '/v1/apple_pay/domains/apwc_1BoJ2MKrZ43eBVAbwqOtiDAK', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_sku.SKUTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_sku.py", line 69, in test_is_deletable
    '/v1/skus/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/skus/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe45582bb38>, 'delete', '/v1/skus/sku_CCiTarxGpuFjAr', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_plan.PlanTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_plan.py", line 67, in test_is_deletable
    '/v1/plans/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/plans/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe45571db00>, 'delete', '/v1/plans/gold', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_recipient.RecipientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_recipient.py", line 64, in test_is_deletable
    '/v1/recipients/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/recipients/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe455ce7e80>, 'delete', '/v1/recipients/rp_1BoJ2NKrZ43eBVAbOlxIQK1Q', {}, None)

======================================================================
FAIL: test_is_deletable (tests.api_resources.test_subscription_item.SubscriptionItemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "…/Vcs/stripe-python/tests/api_resources/test_subscription_item.py", line 71, in test_is_deletable
    '/v1/subscription_items/%s' % resource.id
  File "…/Vcs/stripe-python/tests/helper.py", line 68, in assert_requested
    return self.request_mock.assert_requested(*args, **kwargs)
  File "…/Vcs/stripe-python/tests/request_mock.py", line 83, in assert_requested
    raise exception
  File "…/Vcs/stripe-python/tests/request_mock.py", line 75, in assert_requested
    self.request_spy.assert_called_with(*args)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 316, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
  File "…/Vcs/stripe-python/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 3, in raise_from
AssertionError: Expected call: request(<ANY>, 'delete', '/v1/subscription_items/this_is_a_fake_id_for_deleted_object', <ANY>, <ANY>)
Actual call: request(<stripe.api_requestor.APIRequestor object at 0x7fe455844b70>, 'delete', '/v1/subscription_items/si_CCiTeY6cvtsSog', {}, None)

----------------------------------------------------------------------
Ran 343 tests in 2.465s

FAILED (failures=10)
Test failed: <unittest.runner.TextTestResult run=343 errors=0 failures=10>
error: Test failed: <unittest.runner.TextTestResult run=343 errors=0 failures=10>
sys:1: ResourceWarning: unclosed <socket.socket fd=47, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 43170, 0, 0), raddr=('::1', 12111, 0, 0)>
…
sys:1: ResourceWarning: unclosed <socket.socket fd=87, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::1', 43542, 0, 0), raddr=('::1', 12111, 0, 0)>
ERROR: InvocationError: '…/Vcs/stripe-python/.tox/py36/bin/python -W all -bb -W error::BytesWarning -m coverage.__main__ run setup.py test'
__________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   py36: commands failed
  9.06s user 0.76s system 96% cpu 10.189 total
```

There are also a bunch of ResourceWarnings that should get silenced/fixed probably.

**Comment by ob-stripe** [comment]
Hey @blueyed, thanks for the report! It looks like the tests were (incorrectly) asserting that after deleting a resource, the resource would still be an instance of whatever class it was before being deleted. This used to work because stripe-mock was (also incorrectly) returning fixtures with the `object: <name>` attribute for deleted resources.

@tmaxwell-stripe recently updated the OpenAPI spec and fixtures (used by stripe-mock) to correctly represent deleted resources, and so those tests are now failing. This is easy enough to fix, we just need a new numbered version of stripe-mock.

@tmaxwell-stripe: Mind cutting a new stripe-mock version with the latest OpenAPI spec?

cc @stripe/api-libraries: We should check if other libraries are affected by this issue too.

**Comment by brandur-stripe** [comment]
Doh. Yeah, we might be seeing a few more of these as the OpenAPI spec's accuracy is tightened up.

**Comment by tmaxwell-stripe** [comment]
@ob-stripe OK, I cut a new `stripe-mock` version `v0.9.0` with the latest OpenAPI spec.
