### ISSUE TITLE
Issue using stripe API v1 while trying to retrieve all list items of Customers structure

### ISSUE THREAD

**Issue by thetanja** [stripe/stripe-python#617]
We have encountered an issue using stripe API v1 while trying to retrieve all list items of Customers structure. We had a similar problem with Charges and you solved it. Solution was: "The reason is that pandas.io.json_normalize calls __copy__ and __deep_copy__ functions which calls __setitem__ function [0] and throws the exception.
It will throw this exception when the payment_method_details is an empty string, if the value is null, it will be ok."

More details about the error and code
1. The source code:

```python
import pandas as pd
from pandas.io.json import json_normalize
import stripe

stripe.api_key = 

def extract_data(api_data):
  data_list = pd.DataFrame()
  for item in api_data.auto_paging_iter():
    flatten = json_normalize(item, sep="_")
  data_list = data_list.append(flatten, sort=True)
  return data_list

if __name__ == '__main__':
  charges = stripe.Customer.list(limit=100)
  charges_list = extract_data(charges)
```

```
[2019-09-16 12:19:50,772] {bash_operator.py:127} INFO - Traceback (most recent call last):
[2019-09-16 12:19:50,772] {bash_operator.py:127} INFO - File "stripe_data_retrieve.py", line 52, in <module>
[2019-09-16 12:19:50,772] {bash_operator.py:127} INFO - main()
[2019-09-16 12:19:50,772] {bash_operator.py:127} INFO - File "stripe_data_retrieve.py", line 48, in main
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - retrieve_stripe_data(timestamps_to_fix_format)
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "stripe_data_retrieve.py", line 37, in retrieve_stripe_data
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - stripe_data_list = extract_data(stripe_data, timestamps_to_fix_format)
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "stripe_data_retrieve.py", line 20, in extract_data
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - flatten = json_normalize(item, sep="_")
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/json/_normalize.py", line 266, in json_normalize
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - data = nested_to_record(data, sep=sep, max_level=max_level)
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/json/_normalize.py", line 106, in nested_to_record
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - new_d.update(nested_to_record(v, newkey, sep, level + 1, max_level))
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/json/_normalize.py", line 106, in nested_to_record
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - new_d.update(nested_to_record(v, newkey, sep, level + 1, max_level))
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/json/_normalize.py", line 102, in nested_to_record
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - new_d[newkey] = v
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - File "/home/ubuntu/.local/lib/python3.6/site-packages/stripe/stripe_object.py", line 106, in __setitem__
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - % (k, str(self), k)
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - ValueError: You cannot set shipping_address_city to an empty string. We interpret empty strings as None in requests.You may set {
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - "country": "",
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - "line1": "",
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - "line2": "",
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - "postal_code": "",
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - "state": ""
[2019-09-16 12:19:50,773] {bash_operator.py:127} INFO - }.shipping_address_city = None to delete the property
[2019-09-16 12:19:50,882] {bash_operator.py:131} INFO - Command exited with return code 1
```

2. Python 3.6.8; Stripe 2.36.2

**Comment by ob-stripe** [comment]
@thetanja It looks like Panda's `json_normalize` tries to set a field on a `StripeObject` to an empty string, which is explicitly disallowed.

I'm not sure what your code is supposed to do exactly, but if you don't need the resulting list to contain `StripeObject` instances and only care about the keys/values, you can try converting the `StripeObject` back to a regular `dict`:

```python
flatten = json_normalize(item.to_dict_recursive(), sep="_")
```

**Comment by thetanja** [comment]
Thanks for the info, it works.
