### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes when modifying a customer

### ISSUE THREAD

**Issue by victorct-pronto** [stripe/stripe-python#666]
API version: 2020-03-02; oxxo_beta=v1
Python library: 2.48.0

Whenever I add a card using my frontend I get a card id, after that I do a request to my backend, that makes this card, the default one, but I'm getting an error, the weird thing is that this only happens when adding the first card of a customer:
```

pronto_api_core    | 172.18.0.1 - - [16/Jul/2020 22:47:01] "POST /miportal/save-card HTTP/1.1" 500 -
pronto_api_core    | Traceback (most recent call last):
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
pronto_api_core    |     return self.wsgi_app(environ, start_response)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/packages/wrapt/wrappers.py", line 561, in __call__
pronto_api_core    |     args, kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/api/wsgi_application.py", line 665, in _nr_wsgi_application_wrapper_
pronto_api_core    |     environ, _start_response, transaction)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/api/wsgi_application.py", line 193, in __init__
pronto_api_core    |     self.start_response)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
pronto_api_core    |     response = self.handle_exception(e)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
pronto_api_core    |     return cors_after_request(app.make_response(f(*args, **kwargs)))
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
pronto_api_core    |     return original_handler(e)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/packages/wrapt/wrappers.py", line 561, in __call__
pronto_api_core    |     args, kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/framework_flask.py", line 108, in _nr_wrapper_Flask_handle_exception_
pronto_api_core    |     return wrapped(*args, **kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
pronto_api_core    |     reraise(exc_type, exc_value, tb)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
pronto_api_core    |     raise value.with_traceback(tb)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
pronto_api_core    |     response = self.full_dispatch_request()
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
pronto_api_core    |     rv = self.handle_user_exception(e)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
pronto_api_core    |     return cors_after_request(app.make_response(f(*args, **kwargs)))
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
pronto_api_core    |     return original_handler(e)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/packages/wrapt/wrappers.py", line 561, in __call__
pronto_api_core    |     args, kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/framework_flask.py", line 108, in _nr_wrapper_Flask_handle_exception_
pronto_api_core    |     return wrapped(*args, **kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
pronto_api_core    |     reraise(exc_type, exc_value, tb)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
pronto_api_core    |     raise value.with_traceback(tb)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
pronto_api_core    |     rv = self.dispatch_request()
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
pronto_api_core    |     return self.view_functions[rule.endpoint](**req.view_args)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/packages/wrapt/wrappers.py", line 522, in __call__
pronto_api_core    |     args, kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/framework_flask.py", line 45, in _nr_wrapper_handler_
pronto_api_core    |     return wrapped(*args, **kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
pronto_api_core    |     resp = resource(*args, **kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
pronto_api_core    |     return self.dispatch_request(*args, **kwargs)
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
pronto_api_core    |     resp = meth(*args, **kwargs)
pronto_api_core    |   File "/opt/api/utils/utils.py", line 250, in wrapper
pronto_api_core    |     return func(*args, **_kwargs)
pronto_api_core    |   File "/opt/api/utils/validation_errors.py", line 17, in wrapper
pronto_api_core    |     return func(*args, **kwargs)
pronto_api_core    |   File "/opt/api/utils/business_exception.py", line 33, in wrapper
pronto_api_core    |     return func(*args, **kwargs)
pronto_api_core    |   File "/opt/api/miportal/presentation/resources.py", line 69, in post
pronto_api_core    |     driver_id=user_id, card_token=data.get("card_token")
pronto_api_core    |   File "/opt/api/miportal/domain/usecases.py", line 46, in save_card
pronto_api_core    |     cls._make_card_default(driver=driver, card_id=card.id)
pronto_api_core    |   File "/opt/api/miportal/domain/usecases.py", line 61, in _make_card_default
pronto_api_core    |     data={"default_source": card_id},
pronto_api_core    |   File "/opt/api/payments/data/repositories/payment_gateway_repository.py", line 36, in update_customer
pronto_api_core    |     return self.payment_gateway_source.update_customer(customer_id, data)
pronto_api_core    |   File "/opt/api/payments/data/sources/stripe_driver_api_source.py", line 77, in update_customer
pronto_api_core    |     **data
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/stripe/api_resources/abstract/updateable_api_resource.py", line 11, in modify
pronto_api_core    |     url = "%s/%s" % (cls.class_url(), quote_plus(util.utf8(sid)))
pronto_api_core    |   File "/usr/local/lib/python3.7/urllib/parse.py", line 850, in quote_plus
pronto_api_core    |     string = quote(string, safe + space, encoding, errors)
pronto_api_core    |   File "/usr/local/lib/python3.7/urllib/parse.py", line 834, in quote
pronto_api_core    |     return quote_from_bytes(string, safe)
pronto_api_core    |   File "/usr/local/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
pronto_api_core    |     raise TypeError("quote_from_bytes() expected bytes")
pronto_api_core    | TypeError: quote_from_bytes() expected bytes

```

If you look at the code the error is when executing my function update customer, which does the following:

```
def update_customer(self, customer_id: str, data: Dict) -> Dict:
      ## This function is executed after creating the customer, then I associate the card to the customer
        print(data) ##### {'default_source': 'card_XXXXXXXXXXXXX'}
        return stripe.Customer.modify(
            customer_id,
            stripe_version="2020-03-02; oxxo_beta=v1",
            api_key=ENV.STRIPE_DRIVER_SECRET_KEY,
            **data
        )
```

**Comment by remi-stripe** [comment]
@victorct-pronto Would you be able to provide a bit more details about the request so that we can try to track it down on our end? For example could you try sending also `metadata: {'debugging': 'stripe-python-issues-866'}` to see if it reaches us and if I can spot anything that could cause this?

**Comment by victorct-pronto** [comment]
@remi-stripe It doesn't hit your endpoint, if see on the traceback, the problem occurs when you try build the URL, on this line:

```
pronto_api_core    |   File "/usr/local/lib/python3.7/site-packages/stripe/api_resources/abstract/updateable_api_resource.py", line 11, in modify
pronto_api_core    |     url = "%s/%s" % (cls.class_url(), quote_plus(util.utf8(sid)))
```

**Comment by remi-stripe** [comment]
Would you be able to share code that could reproduce this issue? If not, I think you might have to talk to our support team so that you can share more specific data about what's happening and what exactly is being sent as parameters to the API

**Comment by richardm-stripe** [comment]
Closing for now due to inactivity. Feel free to re-open if you have more information that could help us debug this!

**Comment by alfonsoperez** [comment]
I have reproduced this issue or very similar by simply:

```
stripe.Subscription.delete(None, invoice_now=True, prorate=True)
```

So I wonder if your `customer_id` is being passed `None`.

Maybe a #good-first-issue for someone to provide helpful errors in this case!.

Keep up the great work!.
