### ISSUE TITLE
Subscription.save/modify on cancelled subscription fails with InvalidRequestError: No such subscription

### ISSUE THREAD

**Issue by jayvdb** [stripe/stripe-python#709]
Using v2.55.2, I have retrieved a cancelled subscription, modified the metadata, and then try to use the inherited method `UpdateableAPIResource.save()` to post the results back.

```py
Traceback (most recent call last):
  File "stripe_script.py"
    sub.save()
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/abstract/updateable_api_resource.py", line 20, in save
    self.request(
  File "/usr/lib/python3.8/site-packages/stripe/stripe_object.py", line 243, in request
    response, api_key = requestor.request(method, url, params, headers)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 122, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 373, in interpret_response
    self.handle_error_response(rbody, rcode, resp.data, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 152, in handle_error_response
    raise err
stripe.error.InvalidRequestError: Request req_FdAxInB7Eqe0z9: No such subscription: 'sub_xxx'
```

https://stripe.com/docs/api/subscriptions/update?lang=python says to be using the class method `.modify()` instead.

Using `stripe.Subscription.modify(sub.id, metadata=metadata)` and `stripe.Subscription.modify(sub.id, metadata=metadata, stripe_account=stripe_account)` also have the same result, irrespective of using `metadata=None` or providing a value.

```py
  File "stripe_script.py"
    stripe.Subscription.modify(sub.id, metadata=metadata, stripe_account=stripe_account)
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/abstract/updateable_api_resource.py", line 12, in modify
    return cls._static_request("post", url, **params)
  File "/usr/lib/python3.8/site-packages/stripe/api_resources/abstract/api_resource.py", line 64, in _static_request
    response, api_key = requestor.request(method_, url_, params, headers)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 122, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 373, in interpret_response
    self.handle_error_response(rbody, rcode, resp.data, rheaders)
  File "/usr/lib/python3.8/site-packages/stripe/api_requestor.py", line 152, in handle_error_response
    raise err
stripe.error.InvalidRequestError: Request req_KZCcoO1PDJoeSb: No such subscription: 'sub_xxx'
```

This looks like a stripe backend problem with the error message ("No such subscription...").  I didnt see any clear info in the docs regarding cancelled subscriptions being read-only.  It would be nice to know which fields are locked, and potentially add a 'post-cancelled metadata' to allow adding other data after the subscription is cancelled.  A more informative backend error message would avoid a lot of confusion.

Also perhaps the client side library `.save()` could access the `.status` to provide a better error message if indeed cancelled means read-only.

**Comment by remi-stripe** [comment]
@jayvdb Thanks for reaching out and sorry for the delay on that one. At the moment, canceled subscriptions can be retrieved via the API but they can not be modified or updated and are considered read-only. We are unlikely to add support for this but we should definitely improve the error message in that case! I've flagged internally to see if we can prioritize a fix for this but I'm going to close this out as this isn't a bug with stripe-python itself, I hope it's okay!

**Comment by jayvdb** [comment]
Thanks for clarifying.
