### ISSUE TITLE
AttributeError: module 'requests' has no attribute 'Session'

### ISSUE THREAD

**Issue by DavBE** [stripe/stripe-python#751]
Hello,

Using python 3.10 64 bits on Windows 10 and stripe package 2.63.0, I get the following error : 

```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    customers = stripe.Customer.list()
  File "\venv\lib\site-packages\stripe\api_resources\abstract\listable_api_resource.py", line 23, in list
    response, api_key = requestor.request("get", url, params)
  File "\venv\lib\site-packages\stripe\api_requestor.py", line 119, in request
    rbody, rcode, rheaders, my_api_key = self.request_raw(
  File "\venv\lib\site-packages\stripe\api_requestor.py", line 366, in request_raw
    rcontent, rcode, rheaders = self._client.request_with_retries(
  File "\venv\lib\site-packages\stripe\http_client.py", line 115, in request_with_retries
    return self._request_with_retries_internal(
  File "\venv\lib\site-packages\stripe\http_client.py", line 142, in _request_with_retries_internal
    response = self.request(method, url, headers, post_data)
  File "\venv\lib\site-packages\stripe\http_client.py", line 296, in request
    return self._request_internal(
  File "\venv\lib\site-packages\stripe\http_client.py", line 319, in _request_internal
    self._thread_local.session = self._session or requests.Session()
AttributeError: module 'requests' has no attribute 'Session'
```

Code : 

```
stripe.api_key = 'sk_live_...'
customers = stripe.Customer.list()
```

Any help would be appreciated.

Best regards,

David

**Comment by remi-stripe** [comment]
@DavBE This looks like a bug with your python installation or cache on your end that you can't call `requests.Session()`. Either you don't have `requests` installed or it's mis-configured. You might need to reinstall python first on your machine/environment

**Comment by DavBE** [comment]
@remi-stripe Hi, thanks for your reply. There was indeed an issue with the requests module. Uninstalling/reinstalling it fixed it.
